-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKJACOfMR2NVghx6h
4GjaVndZ4ozwCAAuLNTGhsOWANegCgYIKoZIzj0DAQehRANCAAQ9+OpruncnLZS9
8TqCkSoMA7rHTdWkgjv9rZ/AhrIOpPR/Oh+o9wBHLJ81OYCPBo8hcu3bK7toeO7Q
icbCfafs
-----END PRIVATE KEY-----